version: '3'

services:
  api:
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app  # Mount source code for live changes

  mongo:
    environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=K84BFhiNDz7egnYkE3Tg
    ports:
      - "27017:27017"

  nginx:
    env_file:
      - .env.development
