version: '3'


services:
  api:
    build: ./api
    env_file:
      - .env
    volumes:
      - videos_volume:/usr/src/app/videos
    networks:
        - reddit-reels-network

  mongo:
    restart: unless-stopped
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo_volume:/data/db
    networks:
      - reddit-reels-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    command: mongod --quiet

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    env_file:
      - .env
    ports:
      - "80:80"
    networks:
      - reddit-reels-network


networks:
  reddit-reels-network:


volumes:
  mongo_volume:
  videos_volume: