version: '3'

services:
  api:
    build: ./api
    volumes:
      - videos_volume:/usr/src/app/videos
    networks:
      - reddit-reels-network

  mongo:
    restart: unless-stopped
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo_volume:/data/db
    networks:
      - reddit-reels-network
    command: mongod --quiet

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    networks:
      - reddit-reels-network

networks:
  reddit-reels-network:

volumes:
  mongo_volume:
  videos_volume:
