version: '3'


services:
  api:
    build: api
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
        - reddit-reels-network

  mongo:
    restart: unless-stopped
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo_volume:/data/db
    networks:
      - reddit-reels-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    command: mongod --quiet

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - reddit-reels-network


networks:
  reddit-reels-network:


volumes:
  mongo_volume: