module.exports = {
    rape: "grape",
    kill: "unalived",
    cigarette: "cig",
    cigarettes: "cigs",
    dead: "ded",
    die: "ded",
    died: "ded",
    dies: "ded",
    death: "ded",
    dead: "ded",
    pissed: "angry",
    gun: "weapon",
    guns: "weapons",
    penis: "peni5",
    vagina: "vaj",
    thick: "chunky",
    thic: "chunky",
    fuck: "duck",
    shit: "poo",
    cunt: "c$nt",
    aita: "am i the asshole",
    aitah: "am i the asshole",
    wibta: "would i be the asshole",
    bc: "because",
    fucked: "fudged",
    shit: "poop",
    shitting: "shizzing",
    sex: "seggs",
    porn: "corn",
    suicide: "unalive",
    lesbian: "le$bian",
    gay: "g@y",
    queer: "qu3er",
    abortion: "ab*rtion",
    alcohol: "bevvy",
    murder: "murdoodle",
    blood: "red sauce",
    knife: "sharp thing",
    hate: "dislike",
    naked: "nuddy",
    nude: "no-clothes",
    drunk: "tipsy",
    cocaine: "snowy",
    weed: "greenery",
    terrorist: "bad person",
    bomb: "boom device",
    kidnap: "take away",
    assault: "a-salt",
    homicide: "homi",
    racist: "r@cist",
    sexist: "s3xist",
    offensive: "not-nice",
    masturbate: "self-care",
    prostitute: "pro",
    bitch: "bee",
    whore: "w$re",
    slut: "sl$t",
    damn: "darn",
    hell: "heck",
    addiction: "addicto",
    overdose: "overdo",
    marijuana: "maryj",
    lsd: "l$d",
    meth: "m3th",
    heroin: "hero",
    bully: "meanie",
    trans: "tr@ns",
    transgender: "transg3nder",
    bisexual: "bi$exual",
    depression: "sad feels",
    anxiety: "worries",
    war: "big fight",
    fight: "disagreement",
    violence: "roughness",
    attack: "a-tack",
    threat: "promise",
    toxic: "poison",
    poison: "bad drink",
    illegal: "not-allowed",
    crime: "wrongdo",
    arrest: "grabbed",
    jail: "time out place",
    prison: "big time out place",
    torture: "bad time",
    racism: "race issue",
    discrimination: "unfairness",
    "hate speech": "mean words",
    propaganda: "propa",
    radical: "r@dical",
    extremist: "extreme-o",
    fascist: "f@scist",
    communist: "commie",
    nazi: "n@zi",
    dictatorship: "boss rule",
    drugs: "dru$s",
    assault: "rough up",
    robbery: "take-stuff",
    theft: "takey",
    victim: "victo",
    police: "po-po",
    officer: "offi",
    suicide: "s-thing",
    selfharm: "self-hurt",
    cutting: "slicing",
    mental: "mindy",
    illness: "sicky",
    disorder: "dis-order",
    therapy: "talky time",
    medication: "meds",
    pills: "little circles",
    alcoholic: "drink-lover",
    rehab: "fix-up place",
    abuse: "bad use",
    abusive: "usey-bad",
    trauma: "hard time",
    PTSD: "post-stressy",
    bullying: "big meanie act",
    harass: "bother a lot",
    harassment: "big bother",
    molestation: "bad touch",
    pedophile: "bad grownup",
    stalker: "follow-friend",
    scam: "tricky deal",
    fraud: "fakery",
    slander: "bad talk",
    libel: "write-lie",
    lie: "untruth",
    fake: "not-real",
    conspiracy: "conspire-yarn"
}