name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: SSH and Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd reddit-reels
            git pull
            
            
            # Stop and remove all Docker containers
            sudo docker stop $(sudo docker ps -aq)
            sudo docker rm $(sudo docker ps -aq)
            
            # Remove all Docker images
            sudo docker rmi -f $(sudo docker images -aq)
            
            
            sudo docker-compose down
            sudo docker-compose build
            sudo docker-compose up -d