name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: SSH and Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd reddit-reels
            git pull
            
            sudo docker-compose -f docker-compose.yml -f docker-compose.prod.yml down

            # Optionally, prune unused Docker objects to free up space
            sudo docker system prune -af
              
            # Rebuild and start the services
            sudo docker-compose -f docker-compose.yml -f docker-compose.prod.yml build
            sudo docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d